Increase minAllowedWeights to 1536
opentensor/subtensor_deprecated pull request #11
Opened 2022-08-25 19:13 UTC by Eugene-hu

Abstract
The minAllowedWeights determine the number of weights set by each validator. Overall, increasing this parameter will increase the overall trust in the network. Increasing the number of weights available on the network should lead to a higher trust for the average server and a higher consensus.

Motivation
While change #4 increased the overall trust from T=~0.15 to T=~0.3, there is still room for growth. Currently, only ~30% of the incentive are earned by peers with T>0.5, as opposed to the 50% described in the white paper. We also noticed that the default number of weights was too low compared to the number of weights expected in the latest update. Therefore we are increasing the minAllowedWeights to compensate for this discrepancy

Specification
Param: minAllowedWeights
Initial Value:1024
Suggested Value:1536
Time of Effect: Immediate

2022-08-25 19:15 UTC, shibshib approved these changes

2022-08-25 19:16 UTC, unconst approved these changes
LGTM

2022-08-25 20:15 UTC, isabella618033 requested changes
As we have discussed, I think the time of effect should be after we have fixed the normalisation on the validator side.

=== About the updated peers ===
![image](https://user-images.githubusercontent.com/49876827/186760197-6c091c7f-b763-4c7a-bd1a-cf5d7a37ab88.png)

- about 1/3 of the validators are not updated
- those updated peers suffer from dividend cause they set more weight and it is even harder for them to reach consensus, while it is easier for non-updated peers to reach concensus, thus higher divident.

=== About the weight set by a single validator ===

We can see a almost triangular distribution(?) for the weight set by a validator after the normalisation.
![image](https://user-images.githubusercontent.com/49876827/186760153-4fae060a-bd26-439f-b9b1-8e9191888103.png)

- It means that **a lot of the weight was actually set to non-worthy peers**. eg. with (the orange line plot) uid 2505 setting ~2000 weight, a lot of them actually goes to the bottom ones.
- We should actually normalise it in a way for it to **achieve a sigmoid distribution (or exponential) rather then a triangular distribution**. Which would not worsen the **trust** because there are still the same amount of non-zero weight, but it helps us to achieve a more fair weight set (closer to the raw shapely value). And it can actually help us with the flexibility of setting a even higher **minAllowed Weight**, cause the number of weight we set would not affect the fairness, but only help us to set more weight to honest peer. And the validator could still reach concensus with these vast amount of weight that it set.
- I (we?) think the exponential property of the systems should actually come from the magnitude of the weight (or rank) rather then the trust (if we all agree that trust means if a peer is acting honest. ie. if you are honest, you should actually get about the same trust as anyone else (a uniform distribution))

=== Expected behaviour after increasing minAllowedWeight at this stage=== 

- Trust will increase
- Even more weight would got set to unworthy peer
- The divident of the updated peer would get better.
- The divident of the not updated peer would get worst, cause it is harder for them to reach concensus.

=== Suggestion ===

- we should only update the minAllowedWeight after we make sure the validators are setting weight in a fair proportion.

=== Some other observations about weight / turct / concensus / incentive ===
(TLDR) The incentive is not good, where we do not have appropriate ranking gptj > gpt-large > gpt2. Apparently it is due to the trust/concensus, cause the weight sum is doing good.
![image](https://user-images.githubusercontent.com/49876827/186760460-e18e5916-1e28-4b43-8482-ecba7da06c02.png)

(1) The **weight** sum is good with appropriate ranking gptj > gpt-large > gpt2
![image](https://user-images.githubusercontent.com/49876827/186760393-1b9caa22-c775-41f4-8c95-abfcdd99e4d3.png)

(2) The **trust** is better, but not good enough, where it varies across servers with the same prformance. ie. one of our gptj have trust significantly higher then the other gptj
![image](https://user-images.githubusercontent.com/49876827/186760513-689043f4-8b31-4294-ac0c-03efa7bf0b40.png)

(3) The **concensus** is better, but not good enough, it is widening the difference in trust

2022-08-29 17:19 UTC, opentaco approved these changes

2022-09-12 18:15 UTC, mrseeker commented
Pinging @Eugene-hu to prevent this going stale.

2022-09-21 22:15 UTC, Eugene-hu commented
@mrseeker  Thanks for reminding me of this. This PR is no longer needed, as the new validator does this automatically. Closing for completeness.

2022-09-21 22:15 UTC, closed without merging