Adds a max clip value to replace the max allowed min max ratio
opentensor/subtensor_deprecated pull request #18
Opened 2022-09-06 19:50 UTC by unconst

This PR replaces the max allowed min-max ratio computation in exchange for a max clip check. 
The max clip value checks that the normalized weights do not exceed the max clip value.

A new hyper-parameter MaxClipValue has been added with an initial value equal to u32:MAX = 4,294,967,295
At this initial value, there is no restriction on the u32 weights set by a validator.

2022-09-06 19:57 UTC, shibshib approved these changes

2022-09-07 08:13 UTC, opentaco commented on pallets/subtensor/src/weights.rs
> +        if uid != uids[0] {
Where is it ensured that the weight submitter UID is put first in the `uids` vector?

In Bittensor `convert_weights_and_uids_for_emit()` does not explicitly put the submitter UID first in the submitted weights+uids tensors.

2022-09-07 08:13 UTC, opentaco commented on pallets/subtensor/tests/weights.rs
> +		Subtensor::set_max_weight_limit(u32::MAX/5); // Set max to u32::MAX/2
There is an inconsistency here between `u32::MAX/5` and `u32::MAX/2` in the comment.

2022-09-07 08:13 UTC, opentaco commented on pallets/subtensor/tests/weights.rs
> +		let weight_values: Vec<u32> = vec![1, 1, 1, 1]; // normalizes to u32::MAX/2
Just to clarify, what does `normalizes to u32::MAX/2` mean here and how is `u32::MAX/2` reached here?

2022-09-07 21:05 UTC, Eugene-hu approved these changes

2022-09-09 04:50 UTC, unconst commented on pallets/subtensor/tests/weights.rs
> +		let weight_values: Vec<u32> = vec![1, 1, 1, 1]; // normalizes to u32::MAX/2
Both comments are incorrect.

2022-09-09 07:01 UTC, opentaco approved these changes

2022-09-22 13:32 UTC, shibshib commented
Guys is this good to go? been open for a while.

2022-09-27 18:59 UTC, camfairchild requested changes

2022-09-27 18:59 UTC, camfairchild commented on validator_hyperparameters.md
> +| **validatorSequenceLength**        | 128                  |
Add new hyperparameters here also

2022-09-27 19:10 UTC, camfairchild approved these changes

2022-10-12 16:48 UTC, merged